name: Testing

on:
  #push:
  pull_request:
    branches: [ main ]

jobs:
  check_changed_files:
    name: Check Changed Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get changes
        run: |
          readarray -t changed_files < <(git diff --name-only HEAD^1 HEAD)
          bash ./ci/build.sh "${changed_files[@]}"

