name: Testing

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  check_changed_files:
    name: Check Changed Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changes
        run: |
          export CHANGED_FILES="$(git diff --name-only HEAD^1 HEAD)"
          echo "${CHANGED_FILES}"
          bash ./ci/build.sh
