name: Testing

on:
  #push:
  pull_request:
    branches: [ main ]

jobs:
  check_changed_files:
    name: Check Changed Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Get latest tag (highest version number)
        id: get_latest_tag_version
        run: |
          # Fetches tags explicitly just in case, then gets the latest tag based on version sorting
          git fetch --tags --force
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          echo "Latest Tag (Version Sort): $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Get latest tag (most recent commit date)
        id: get_latest_tag_date
        run: |
          # Describes the most recent tag reachable from the current commit
          # This is often useful in CI/CD contexts
          latest_tag=$(git describe --tags --abbrev=0)
          echo "Latest Tag (Reachable): $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT
      - name: Use the tag from version sort
        run: echo "Using tag ${{ steps.get_latest_tag_version.outputs.tag }}"

      - name: Use the tag from most recent reachable
        run: echo "Using tag ${{ steps.get_latest_tag_date.outputs.tag }}"

      - name: Get changes
        run: |
          export
          readarray -t changed_files < <(git diff --name-only HEAD^1 HEAD)
          bash ./ci/build.sh "${changed_files[@]}"
